server:
  port: 8106
spring:
  application:
    name: ms-bank-credit-service
 # config:
  #  import: optional:configserver:http://ms-bank-config-server:8888
  data: 
    mongodb:
     host: localhost
     port: 27017
     database: Bank 
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
    
client.msbankproductrule.url: http://localhost:8080/product